// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace ShopApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240724174932_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Video Games"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Book"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Stationery"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ProductName = "GTA V",
                            ProductPrice = 14.98m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ProductName = "The Witcher 3",
                            ProductPrice = 29.99m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            ProductName = "Celeste",
                            ProductPrice = 10.49m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            ProductName = "Paper, Please",
                            ProductPrice = 9.99m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            ProductName = "Don't Starve",
                            ProductPrice = 3.29m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            ProductName = "The Brothers Karamozov",
                            ProductPrice = 19.95m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            ProductName = "Lamy Fountain Pen",
                            ProductPrice = 25.35m
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
