// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApp.Models;

#nullable disable

namespace ShopApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "GTA V",
                            ProductPrice = 14.98m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "The Witcher 3",
                            ProductPrice = 29.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Celeste",
                            ProductPrice = 10.49m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "Paper, Please",
                            ProductPrice = 9.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductName = "Don't Starve",
                            ProductPrice = 3.29m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
